4.1

In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('img1.png', 1)

4.2

In [3]:
retval, corners = cv2.findChessboardCorners(img, (24,17), None) 

In [4]:
print(corners)

[[[ 394.29108  791.2645 ]]

 [[ 409.39203  791.1205 ]]

 [[ 424.80472  792.13873]]

 [[ 440.69943  792.08124]]

 [[ 456.7048   792.3981 ]]

 [[ 472.66364  792.6077 ]]

 [[ 488.99585  793.0634 ]]

 [[ 504.72165  793.3816 ]]

 [[ 520.64984  793.9748 ]]

 [[ 536.8101   793.58075]]

 [[ 552.8645   794.34845]]

 [[ 569.51587  794.2261 ]]

 [[ 585.81305  794.3726 ]]

 [[ 602.36743  794.50323]]

 [[ 618.67413  794.60077]]

 [[ 635.1011   794.7454 ]]

 [[ 651.7561   794.8676 ]]

 [[ 668.22064  794.746  ]]

 [[ 684.863    795.33777]]

 [[ 701.2876   794.8793 ]]

 [[ 718.12854  795.18536]]

 [[ 734.37115  794.8175 ]]

 [[ 751.09174  795.1148 ]]

 [[ 767.53766  794.75146]]

 [[ 394.3933   806.7959 ]]

 [[ 410.23233  807.5955 ]]

 [[ 425.4996   807.67175]]

 [[ 440.8316   808.3187 ]]

 [[ 456.8668   808.5438 ]]

 [[ 473.02594  808.7212 ]]

 [[ 488.84448  809.2431 ]]

 [[ 504.72482  809.916  ]]

 [[ 520.8891   809.5524 ]]

 [[ 536.9456   810.37744]]

 [[ 553.4509   810.29486]]

 [[ 569.70233  810.5

4.3

In [5]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
objp = np.zeros((24*17,3), np.float32)
objp[:,:2] = np.mgrid[0:24,0:17].T.reshape(-1,2)
objpoints = []
imgpoints = []
if retval == True:
    objpoints.append(objp)
    corners2 = cv2.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
    imgpoints.append(corners)
    cv2.drawChessboardCorners(img, (24, 17), corners2, retval)
    cv2.imshow('img', img)
    cv2.imwrite("img1points.jpg", img)
    cv2.waitKey(500)


In [6]:
cv2.destroyAllWindows()

4.4

In [7]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [8]:
print("ret = ", ret)
print("mtx = ", mtx)
print("dist = ", dist)
print("rvecs = ", rvecs)
print("tvecs = ", tvecs)

ret =  0.22975377370739775
mtx =  [[1.00520523e+03 0.00000000e+00 7.91264339e+02]
 [0.00000000e+00 1.01544867e+03 5.20980956e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist =  [[-0.20625468  0.1989532  -0.00082261 -0.01649139 -0.18016533]]
rvecs =  (array([[-0.02364562],
       [ 0.03777226],
       [-0.00948411]]),)
tvecs =  (array([[-24.33164186],
       [ 16.51999428],
       [ 60.43366947]]),)


4.6

In [9]:
img = cv2.imread('img5.png')
h,  w = img.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

dst = cv2.undistort(img, mtx, dist, None, newcameramtx)

x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('calibresult1.png', dst)

True

4.7

In [15]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objp = np.zeros((24*17,3), np.float32)
objp[:,:2] = np.mgrid[0:24,0:17].T.reshape(-1,2)

objpoints = [] 
imgpoints = []
images = ["img1.png", "img2.png", "img3.png", "img4.png"]
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    ret, corners = cv2.findChessboardCorners(gray, (24,17), None)
    
    if ret == True:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        cv2.drawChessboardCorners(img, (24,17), corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(500)
cv2.destroyAllWindows()

In [16]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [18]:

img = cv2.imread('img5.png')
h,  w = img.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

dst = cv2.undistort(img, mtx, dist, None, newcameramtx)
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('calibresult2.png', dst)

True